# Generated by Django 5.1.1 on 2024-09-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sinais.person')),
            ],
        ),
    ]
